/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ed7f1ddf-2829-4038-b1bd-d9ef04fffd7a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Fi4Nl3wpS",
    "aws_user_pools_web_client_id": "4fp4lk0c81iq9bm3jgk6lufcev",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://zau7haehfvefreat7v2tiovf3a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-bzg3tzwkxbhsfnimwxfgo4xcfu",
    "aws_user_files_s3_bucket": "projectgame19a48c45f3464609b0ca81688295d3b6102134-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};
export default awsmobile;

